#  test:
#    image: circleci/ruby:2.5.1-node
#    environment:
#      - RAILS_ENV=test
#      - RAILS_MASTER_KEY=9ccfd6e620c80aae1bcd36c509407778
#      - POSTGRES_USER=circleci
#      - POSTGRES_DB=circle_test
#    commands:
#      - bundle install && yarn install
#      - bundle exec rails db:test:prepare
#      - bundle exec rspec
#  branches: disabled

pipeline:
  build-app-staging:
    image: plugins/docker
    repo: registry.evilcorp.gq/matteojoliveau/dev-cms
    registry: registry.evilcorp.gq
    tags: "${DRONE_COMMIT_SHA:0:8}"
    when:
      event: [push]
      branch: develop
    secrets: [rails_master_key]
    build_args_from_env: [ RAILS_MASTER_KEY ]

  build-db-staging:
    image: plugins/docker
    repo: registry.evilcorp.gq/matteojoliveau/dev-cms-init-db
    registry: registry.evilcorp.gq
    tags: "${DRONE_COMMIT_SHA:0:8}"
    dockerfile: Dockerfile.init-db
    when:
      event: [push]
      branch: develop
    secrets: [rails_master_key]
    build_args_from_env: [ RAILS_MASTER_KEY ]

  build-app-production:
    image: plugins/docker
    repo: registry.evilcorp.gq/matteojoliveau/dev-cms
    registry: registry.evilcorp.gq
    tags: latest
    when:
      event: [push, tag]
      branch: master
    secrets: [rails_master_key]
    build_args_from_env: [ RAILS_MASTER_KEY ]

  build-db-production:
    image: plugins/docker
    repo: registry.evilcorp.gq/matteojoliveau/dev-cms-init-db
    registry: registry.evilcorp.gq
    tags: "${DRONE_COMMIT_SHA:0:8}"
    dockerfile: Dockerfile.init-db
    when:
      event: [push, tag]
      branch: master
    secrets: [rails_master_key]
    build_args_from_env: [ RAILS_MASTER_KEY ]

services:
  database:
    image: circleci/postgres:10.4-alpine
    environment:
      - POSTGRES_USER=circleci
      - POSTGRES_DB=circle_test
