version: '3.1'

services:
  dev_db:
    image: postgres:10.4-alpine
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: dev_development
