FROM circleci/ruby:2.5.1-node

USER root

RUN mkdir -p /usr/local/app
RUN useradd -ms /bin/bash rails
RUN chown rails /usr/local/app

USER rails

WORKDIR /usr/local/app

COPY Gemfile /user/local/app

RUN bundle install

COPY . /user/local/app

ENTRYPOINT ["bundle", "exec", "rails", "db:migrate", "db:seed"]

